---
- hosts: control
  strategy: free 
  gather_facts: False
  become: true
  tasks:
  - name: Setting Hostname
    command: hostnamectl set-hostname control.test.example.com
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding control address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.60 control.test.example.com control
      create: yes
  - name: Adding Repo address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.59 repo.test.example.com repo
      create: yes
  - name: Adding node1 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.61 node1.test.example.com node1
      create: yes
  - name: Adding node2 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.62 node2.test.example.com node2
      create: yes
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
#  - name: Generating RSA Key
#    command : ssh-keygen -q -t rsa -f /home/vagrant/.ssh/id_rsa -C "" -N ""
  - name: Generating RSA Key
    openssh_keypair:
      path: /home/vagrant/.ssh/id_rsa
      force: True
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
        #!/bin/bash
        #
        echo -e '       
        #            _            _           _          _           _          _           _     
        #          /\ \          /\ \        /\ \     _ /\ \        /\ \       /\ \        _\ \   
        #         /  \ \        /  \ \      /  \ \   /\_\_\ \      /  \ \     /  \ \      /\__ \  
        #        / /\ \ \      / /\ \ \    / /\ \ \_/ / /\__ \    / /\ \ \   / /\ \ \    / /_ \_\ 
        #       / / /\ \ \    / / /\ \ \  / / /\ \___/ / /_ \ \  / / /\ \_\ / / /\ \ \  / / /\/_/ 
        #      / / /  \ \_\  / / /  \ \_\/ / /  \/____/ / /\ \ \/ / /_/ / // / /  \ \_\/ / /      
        #     / / /    \/_/ / / /   / / / / /    / / / / /  \/_/ / /__\/ // / /   / / / / /       
        #    / / /         / / /   / / / / /    / / / / /     / / /_____// / /   / / / / / ____   
        #   / / /________ / / /___/ / / / /    / / / / /     / / /\ \ \ / / /___/ / / /_/_/ ___/\ 
        #  / / /_________/ / /____\/ / / /    / / /_/ /     / / /  \ \ / / /____\/ /_______/\__\/ 
        #  \/____________\/_________/\/_/     \/_/\_\/      \/_/    \_\\/_________/\_______\/     
        '"#
        #
        # You are logged into \"`hostname`\" as user \"`whoami`\"
        # This system is running `cat /etc/redhat-release`
        # kernel is `uname -r`
        #
        "