---
- name: Installing keys
  hosts: control
  become: yes
  become_user: user
  ignore_errors: yes
  tasks: 
  - name: Sending Key to node1
    expect:
      command: ssh-copy-id -i /home/user/.ssh/id_rsa.pub user@node1.test.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        "user@node1.test.example.com's password": 'password'
        'password': 'password'
        '\]\$': 'logout'
      timeout: 10
  - name: Sending Key to node2
    expect:
      command: ssh-copy-id -i /home/user/.ssh/id_rsa.pub user@node2.test.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        "user@node2.test.example.com's password": 'password'
        'password': 'password'
        '\]\$': 'logout'
      timeout: 10