---
- name: Setting Up Repo Server
  hosts: repo
  strategy: free
  become: true
  gather_facts: false
  ignore_errors: true
  tasks:
  - name: Setting Hostname
    hostname: name=repo.ansi.example.com
  - name: Creating User Account
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Checking Sudoers Configuration
    lineinfile:
      path: /etc/sudoers
      regexp: '^# %users  localhost'
      insertafter: '^# %users  localhost'
      line: 'user ALL=(ALL) NOPASSWD: ALL'
      state: present
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Creating Repo File
    file:
      path: /etc/yum.repos.d/rpms.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    blockinfile:
      dest: /etc/yum.repos.d/rpms.repo
      block: |
       [rpms]
       name=rpms
       baseurl=file:///var/www/html/rpms
       gpgcheck=0
       enabled=1
  - name: Building host file
    copy:
      dest: /etc/hosts
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n192.168.55.59 repo.ansi.example.com repo192.168.55.60 control.ansi.example.com control\n192.168.55.61 node1.ansi.example.com node1\n192.168.55.62 node2.ansi.example.com node2"
      force: yes
  - name: Enabling services
    service: 
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - httpd
      - firewalld
  - name: Enabling Firewall Services
    firewalld:
      service: "{{ item }}"
      state: enabled
      immediate: yes
      permanent: yes
    with_items:
      - http
      - https
      - ntp
      - dns
      - kerberos
      - ldap
      - ftp
  - name: Restarting Firewalld
    service: name=firewalld state=restarted
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Setting SELinux To Permissive
    selinux:
      state: disabled
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #           _          _           _         _       
         #          /\ \       /\ \        /\ \      /\ \     
         #         /  \ \     /  \ \      /  \ \    /  \ \    
         #        / /\ \ \   / /\ \ \    / /\ \ \  / /\ \ \   
         #       / / /\ \_\ / / /\ \_\  / / /\ \_\/ / /\ \ \  
         #      / / /_/ / // /_/_ \/_/ / / /_/ / / / /  \ \_\ 
         #     / / /__\/ // /____/\   / / /__\/ / / /   / / / 
         #    / / /_____// /\____\/  / / /_____/ / /   / / /  
         #   / / /\ \ \ / / /______ / / /     / / /___/ / /   
         #  / / /  \ \ / / /_______/ / /     / / /____\/ /    
         #  \/_/    \_\\/__________\/_/      \/_________/     
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into \"`hostname`\" as the \"`whoami`\" account.
         # This system is running `cat /etc/redhat-release`
         "
...