---
- hosts: control
  tasks: 
  - name: Welcome to the Ansible 2.3 Study/Test Environment!
    debug:
      msg:
        - 'Next Steps: Accessing The Systems:'
        - '- Control - 192.168.55.60'
        - '- Node 1 - 192.168.55.61'
        - '- Node 2 - 192.168.55.62'
        - '- Username - user or root'
        - '- Password - password'
        - '- For root - use `sudo` or `sudo su`'
        - '- Access example - ssh user@192.168.55.60'